project:
  type: website
  preview:
    browser: true
    
execute:
  freeze: auto
    
resources:
  stars_simmer/data/arrivals.csv

website:
  title: "STARS: WASM"
  image: "quarto_files/nihr.png"
  favicon: "quarto_files/stars.png"
  repo-url: https://github.com/pythonhealthdatascience
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left:  |
      [UK Research and Innovation](https://gtr.ukri.org/projects?ref=MR%2FZ503915%2F1)
    center:     
      - text: "License"
        href: quarto_files/txt/LICENSE.md
      - text: "Citation"
        href: quarto_files/txt/citation.md
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience
  navbar:
    logo: "quarto_files/stars.png"
    left:
      - href: index.qmd
        text: Treatment Centre Simulation Model
      - about.qmd
  sidebar:
    style: "floating"
    background: "#88a2c2"
    alignment: center
    collapse-level: 1
    contents:
      - text: "RUNNING THE MODEL"
      - section: "About us"
        contents:
          - quarto_files/txt/about_stars.qmd
      - section: "Model code"
        contents: 
          - stars_simmer/model.qmd
          - stars_simmer/model_int.qmd


format:
  html:
    theme: cosmo

    toc: true

editor: visual

